os:
    Linux:
        # https://github.com/conan-io/conan/issues/3972#issuecomment-1722591941
        libc:
            null:
            glibc:
                version: ["2.0", "2.1", "2.2", "2.3", "2.4", "2.5", "2.6", "2.7",
                          "2.8", "2.9", "2.10", "2.11", "2.12", "2.13", "2.14",
                          "2.15", "2.16", "2.17", "2.18", "2.19", "2.20", "2.21",
                          "2.22", "2.23", "2.24", "2.25", "2.26", "2.27", "2.28",
                          "2.29", "2.30", "2.31", "2.32", "2.33", "2.34", "2.35",
                          "2.36", "2.37", "2.38"]
            musl:
                version: ["0.9", "1.0", "1.1", "1.2"]
    Macos:
        # Override the Conan available list
        version: [null, "13.0", "13.5"]