name: "Setup Conan"
description: "Install and configure the conan client for use in the user-management project's back-end"
runs:
  using: "composite"
  steps:
    - run: python3 -m pip install -r backend/requirements.txt
      shell: bash
    - run: conan config init --force
      shell: bash
    - run: conan config install -t dir backend/.conan
      shell: bash
