name: 'Setup Conan'
description: 'Install and configure the conan client'
inputs:
  conan_cache:
    description: 'Cache key for the `~/.conan/data` folder'
    required: true
  libcxx:
    description: 'C++ standard ABI version to use'
    required: false
    default: 'libstdc++11'
runs:
  using: "composite"
  steps:
    - uses: actions/cache@v2
      with:
        path: ~/.conan/data
        key: ${{ inputs.conan_cache }}
    - run: python3 -m pip install conan --upgrade
      shell: bash
    - run: conan config set general.revisions_enabled=1
      shell: bash
    - run: conan config install backend/.conan/settings.yml
      shell: bash
    - run: conan profile new default --detect
      shell: bash
    - run: conan profile update settings.compiler.libcxx=${{ inputs.libcxx }} default
      shell: bash
    - run: conan remote list
      shell: bash
