FROM node:14-alpine3.12 as install
ADD yarn.lock yarn.lock
RUN yarn install

FROM install as build
ARG api_url
ADD . .
RUN yarn build --env.API_URL=${api_url}

FROM nginx:1.19.6-alpine
COPY --from=build dist/ /usr/share/nginx/html
