function(PACK_SCHEMAS SCHEMAS)
   set(SCHEMAS_HEADER "${CMAKE_BINARY_DIR}/schemas.hpp")

   file(WRITE "${SCHEMAS_HEADER}.tmp" "\
// Auto-generated by cmake script.\n\
\n\
#include <nlohmann/json.hpp>\n\
\n\
namespace api\n\
{\n")

   foreach(SCHEMA ${SCHEMAS})
      string(MAKE_C_IDENTIFIER "${SCHEMA}" VAR)
      file(APPEND "${SCHEMAS_HEADER}.tmp" "   static json \"${VAR}\" = R\"-auto-generated-(")
      file(READ "${SCHEMA}" RAW)
      file(APPEND "${SCHEMAS_HEADER}.tmp" "${RAW}")
      file(APPEND "${SCHEMAS_HEADER}.tmp" ")-auto-generated-\"_json;\n")
   endforeach()

   file(APPEND "${SCHEMAS_HEADER}.tmp" "}\n")

   configure_file("${SCHEMAS_HEADER}.tmp" "${SCHEMAS_HEADER}" COPYONLY)
endfunction(PACK_SCHEMAS)
