name: 'Determine Version'
description: 'Calculates the version tag based off the git reference. SemVer tags are presevered, default branch is latest, other branch are untouched, PRs output alternate ID'
inputs:
  github-ref:
    description: 'The current reference point for the version'
    required: true
  unique-alt-id:
    description: 'The version to return when it is pull request'
    required: true
outputs:
  build-version: 
    description: "Build Version"
    value: ${{ steps.cal.outputs.version }}
runs:
  using: "composite"
  steps:
  - id: cal
    run: |
      VERSION=$(echo "${{ inputs.github-ref }}" | sed -e 's,.*/\(.*\),\1,')
      [[ "${{ inputs.github-ref }}" == "refs/tags/"* ]] && VERSION=$(echo $VERSION | sed -e 's/^v//')
      [ "$VERSION" == "main" ] && VERSION=latest
      [ "$VERSION" == "merge" ] && VERSION=$(echo "${{ inputs.unique-alt-id }}")
      echo "version=$VERSION" >> $GITHUB_OUTPUT
    shell: bash
