name: "Setup Artifactory NPM Registry"
description: "Configures the default global registry to be that hosted by a specific Artifactory instance"
inputs:
  registry:
    description: "registry"
    required: true
  auth_token:
    description: "_auth"
    required: true
  email:
    description: "email"
    required: true
runs:
  using: "composite"
  steps:
    - shell: bash
      run: |
        REG_SCOPE=$( echo "${{ inputs.registry }}" | awk -F'^http[s]?:' '{print $2}')
        echo 'registry=${{ inputs.registry }}' > ~/.npmrc
        echo "$REG_SCOPE:_password=${{ inputs.auth_token }}" >> ~/.npmrc
        echo "$REG_SCOPE:username=${{ inputs.email }}" >> ~/.npmrc
        echo "$REG_SCOPE:email=${{ inputs.email }}" >> ~/.npmrc
        echo "$REG_SCOPE:always-auth=true" >> ~/.npmrc
