name: "Setup Artifactory NPM Registry"
description: "Configures the default global registry to be that hosted by a specific Artifactory instance"
inputs:
  registry:
    description: "registry"
    required: true
  auth_token:
    description: "_auth"
    required: true
  email:
    description: "email"
    required: true
runs:
  using: "composite"
  steps:
    - shell: bash
      run: |
        echo '_auth = ${{ inputs.auth_token }}' > ~/.npmrc
        echo 'always-auth = true' >> ~/.npmrc
        echo 'email = ${{ inputs.email }}' >> ~/.npmrc
        echo 'registry = ${{ inputs.registry }}' >> ~/.npmrc
