name: Auto Label Conflicts
on:
  push:
    branches: [main]
  pull_request:
    types: [opened, synchronize, reopened]
    branches: [main]

jobs:
  auto_label:
    runs-on: ubuntu-latest
    steps:
      - uses: prince-chrismc/label-merge-conflicts-action@v3
        with:
          conflict_label_name: 'has conflicts'
          github_token: ${{ secrets.GITHUB_TOKEN }}
