name: Label Pull Requests
on:
  push:
    branches: [master]
  pull_request:
    types: [opened, synchronize, reopened]
    branches: [master]

jobs:
  auto_label:
    name: Merge Conflicts
    runs-on: ubuntu-latest
    steps:
      - uses: prince-chrismc/label-merge-conflicts-action@v1
        with:
          conflict_label_name: 'has conflicts'
          github_token: ${{ secrets.GITHUB_TOKEN }}
